const movies = {
  page: 20,
  results: [
    {
      adult: false,
      backdrop_path: "/tC78Pck2YCsUAtEdZwuHYUFYtOj.jpg",
      genre_ids: [28, 53, 80],
      id: 926393,
      original_language: "en",
      original_title: "The Equalizer 3",
      overview:
        "Robert McCall finds himself at home in Southern Italy but he discovers his friends are under the control of local crime bosses. As events turn deadly, McCall knows what he has to do: become his friends' protector by taking on the mafia.",
      popularity: 102.592,
      poster_path: "/b0Ej6fnXAP8fK75hlyi2jKqdhHz.jpg",
      release_date: "2023-08-30",
      title: "The Equalizer 3",
      video: false,
      vote_average: 7.3,
      vote_count: 2852,
    },
    {
      adult: false,
      backdrop_path: "/pcDc2WJAYGJTTvRSEIpRZwM3Ola.jpg",
      genre_ids: [28, 12, 14],
      id: 791373,
      original_language: "en",
      original_title: "Zack Snyder's Justice League",
      overview:
        "Determined to ensure Superman's ultimate sacrifice was not in vain, Bruce Wayne aligns forces with Diana Prince with plans to recruit a team of metahumans to protect the world from an approaching threat of catastrophic proportions.",
      popularity: 75.77,
      poster_path: "/tnAuB8q5vv7Ax9UAEje5Xi4BXik.jpg",
      release_date: "2021-03-18",
      title: "Zack Snyder's Justice League",
      video: false,
      vote_average: 8.147,
      vote_count: 9873,
    },
    {
      adult: false,
      backdrop_path: "/9X7YweCJw3q8Mcf6GadxReFEksM.jpg",
      genre_ids: [28, 18, 878],
      id: 263115,
      original_language: "en",
      original_title: "Logan",
      overview:
        "In the near future, a weary Logan cares for an ailing Professor X in a hideout on the Mexican border. But Logan's attempts to hide from the world and his legacy are upended when a young mutant arrives, pursued by dark forces.",
      popularity: 72.752,
      poster_path: "/fnbjcRDYn6YviCcePDnGdyAkYsB.jpg",
      release_date: "2017-02-28",
      title: "Logan",
      video: false,
      vote_average: 7.822,
      vote_count: 19059,
    },
    {
      adult: false,
      backdrop_path: "/zhoR3SwYxXyKzGwbz4DBgkyeFfv.jpg",
      genre_ids: [10749, 18, 35],
      id: 1139566,
      original_language: "es",
      original_title: "A través de mi ventana 3: A través de tu mirada",
      overview:
        "After the events of the summer, Ares and Raquel they don't see a way forward in their relationship and decide to go separate ways. But when they meet again in the winter in Barcelona, the love and desire they feel for each other is undeniable. Will they be able to find a way to get back together?",
      popularity: 100.035,
      poster_path: "/gwpTgtwVAwmvivBN8rAQABpx9Am.jpg",
      release_date: "2024-02-23",
      title: "Through My Window 3: Looking at You",
      video: false,
      vote_average: 6.966,
      vote_count: 491,
    },
    {
      adult: false,
      backdrop_path: "/bSvUW4JQ6g4QiKvwejcfcPRd4Ke.jpg",
      genre_ids: [12, 35, 10751, 14],
      id: 118,
      original_language: "en",
      original_title: "Charlie and the Chocolate Factory",
      overview:
        "A young boy wins a tour through the most magnificent chocolate factory in the world, led by the world's most unusual candy maker.",
      popularity: 83.14,
      poster_path: "/iKP6wg3c6COUe8gYutoGG7qcPnO.jpg",
      release_date: "2005-07-13",
      title: "Charlie and the Chocolate Factory",
      video: false,
      vote_average: 7.052,
      vote_count: 14975,
    },
    {
      adult: false,
      backdrop_path: "/iEFuHjqrE059SmflBva1JzDJutE.jpg",
      genre_ids: [16, 14, 28, 10749, 10751],
      id: 496450,
      original_language: "fr",
      original_title: "Miraculous - le film",
      overview:
        "After a guardian of magical jewels turns an awkward girl and a popular boy into superheroes, they can never reveal their identities — even to each other.",
      popularity: 122.667,
      poster_path: "/dQNJ8SdCMn3zWwHzzQD2xrphR1X.jpg",
      release_date: "2023-07-05",
      title: "Miraculous: Ladybug & Cat Noir, The Movie",
      video: false,
      vote_average: 7.656,
      vote_count: 842,
    },
    {
      adult: false,
      backdrop_path: "/kGzFbGhp99zva6oZODW5atUtnqi.jpg",
      genre_ids: [18, 80],
      id: 240,
      original_language: "en",
      original_title: "The Godfather Part II",
      overview:
        "In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.",
      popularity: 94.615,
      poster_path: "/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg",
      release_date: "1974-12-20",
      title: "The Godfather Part II",
      video: false,
      vote_average: 8.575,
      vote_count: 12273,
    },
    {
      adult: false,
      backdrop_path: "/lLQZbBom0IsdQLhe1n9J9SpMzSR.jpg",
      genre_ids: [16, 18, 14],
      id: 1086591,
      original_language: "ja",
      original_title: "青春ブタ野郎はランドセルガールの夢を見ない",
      overview:
        "Finally, the day of Mai's high school graduation has arrived. While Sakuta eagerly waits for his girlfriend, an elementary schooler who looks exactly like her appears before him. Suspicious, and for all the wrong reasons... Meanwhile, Sakuta and Kaede's father suddenly calls, saying that their mother wants to see her daughter. She was hospitalized because Kaede's condition had been too much for her to bear, so what could she possibly want now?",
      popularity: 84.141,
      poster_path: "/AuXbMRrtfFNVNSq5Dk0gBVXFGZy.jpg",
      release_date: "2023-12-01",
      title: "Rascal Does Not Dream of a Knapsack Kid",
      video: false,
      vote_average: 7.844,
      vote_count: 32,
    },
    {
      adult: false,
      backdrop_path: "/hMl124Go2Ed9Qu8VsPLiA3nBSMk.jpg",
      genre_ids: [28, 18, 36],
      id: 1579,
      original_language: "en",
      original_title: "Apocalypto",
      overview:
        "Set in the Mayan civilization, when a man's idyllic presence is brutally disrupted by a violent invading force, he is taken on a perilous journey to a world ruled by fear and oppression where a harrowing end awaits him. Through a twist of fate and spurred by the power of his love for his woman and his family he will make a desperate break to return home and to ultimately save his way of life.",
      popularity: 79.605,
      poster_path: "/cRY25Q32kDNPFDkFkxAs6bgCq3L.jpg",
      release_date: "2006-12-07",
      title: "Apocalypto",
      video: false,
      vote_average: 7.582,
      vote_count: 5459,
    },
    {
      adult: false,
      backdrop_path: "/6XVqVAMOsKL5C26pHesiAawuGYW.jpg",
      genre_ids: [27, 53],
      id: 630586,
      original_language: "en",
      original_title: "Wrong Turn",
      overview:
        "Jen and a group of friends set out to hike the Appalachian Trail. Despite warnings to stick to the trail, the hikers stray off course—and cross into land inhabited by The Foundation, a hidden community of mountain dwellers who use deadly means to protect their way of life.",
      popularity: 78.845,
      poster_path: "/4U1SBHmwHkNA0eHZ2n1CuiC1K1g.jpg",
      release_date: "2021-01-26",
      title: "Wrong Turn",
      video: false,
      vote_average: 5.968,
      vote_count: 1107,
    },
    {
      adult: false,
      backdrop_path: "/921vUyXdfIYpaXqu5Lnf3nVb4IJ.jpg",
      genre_ids: [16, 28, 14],
      id: 810693,
      original_language: "ja",
      original_title: "劇場版 呪術廻戦 0",
      overview:
        "Yuta Okkotsu is a nervous high school student who is suffering from a serious problem—his childhood friend Rika has turned into a curse and won't leave him alone. Since Rika is no ordinary curse, his plight is noticed by Satoru Gojo, a teacher at Jujutsu High, a school where fledgling exorcists learn how to combat curses. Gojo convinces Yuta to enroll, but can he learn enough in time to confront the curse that haunts him?",
      popularity: 85.585,
      poster_path: "/23oJaeBh0FDk2mQ2P240PU9Xxfh.jpg",
      release_date: "2021-12-24",
      title: "Jujutsu Kaisen 0",
      video: false,
      vote_average: 8.172,
      vote_count: 1364,
    },
    {
      adult: false,
      backdrop_path: "/2q75qMwDijJPVbTp6SDDojjEEXg.jpg",
      genre_ids: [35],
      id: 38365,
      original_language: "en",
      original_title: "Grown Ups",
      overview:
        "After their high school basketball coach passes away, five good friends and former teammates reunite for a Fourth of July holiday weekend.",
      popularity: 71.493,
      poster_path: "/cQGM5k1NtU85n4TUlrOrwijSCcm.jpg",
      release_date: "2010-06-24",
      title: "Grown Ups",
      video: false,
      vote_average: 6.4,
      vote_count: 6006,
    },
    {
      adult: false,
      backdrop_path: "/xGzoTqbOlCR4mAzeRs4PB53i8c7.jpg",
      genre_ids: [18, 10749],
      id: 296096,
      original_language: "en",
      original_title: "Me Before You",
      overview:
        "A small town girl is caught between dead-end jobs. A high-profile, successful man becomes wheelchair bound following an accident. The man decides his life is not worth living until the girl is hired for six months to be his new caretaker. Worlds apart and trapped together by circumstance, the two get off to a rocky start. But the girl becomes determined to prove to the man that life is worth living and as they embark on a series of adventures together, each finds their world changing in ways neither of them could begin to imagine.",
      popularity: 87.466,
      poster_path: "/Ia3dzj5LnCj1ZBdlVeJrbKJQxG.jpg",
      release_date: "2016-06-01",
      title: "Me Before You",
      video: false,
      vote_average: 7.93,
      vote_count: 12240,
    },
    {
      adult: false,
      backdrop_path: "/xZ2we4gdiwQmg6D1w9qHlAm5yIf.jpg",
      genre_ids: [35, 12, 14, 16, 10751],
      id: 10192,
      original_language: "en",
      original_title: "Shrek Forever After",
      overview:
        "A bored and domesticated Shrek pacts with deal-maker Rumpelstiltskin to get back to feeling like a real ogre again, but when he's duped and sent to a twisted version of Far Far Away—where Rumpelstiltskin is king, ogres are hunted, and he and Fiona have never met—he sets out to restore his world and reclaim his true love.",
      popularity: 91.678,
      poster_path: "/6HrfPZtKcGmX2tUWW3cnciZTaSD.jpg",
      release_date: "2010-05-16",
      title: "Shrek Forever After",
      video: false,
      vote_average: 6.379,
      vote_count: 7242,
    },
    {
      adult: false,
      backdrop_path: "/wdwcOBMkt3zmPQuEMxB3FUtMio2.jpg",
      genre_ids: [12, 28, 878],
      id: 271110,
      original_language: "en",
      original_title: "Captain America: Civil War",
      overview:
        "Following the events of Age of Ultron, the collective governments of the world pass an act designed to regulate all superhuman activity. This polarizes opinion amongst the Avengers, causing two factions to side with Iron Man or Captain America, which causes an epic battle between former allies.",
      popularity: 125.16,
      poster_path: "/rAGiXaUfPzY7CDEyNKUofk3Kw2e.jpg",
      release_date: "2016-04-27",
      title: "Captain America: Civil War",
      video: false,
      vote_average: 7.445,
      vote_count: 22478,
    },
    {
      adult: false,
      backdrop_path: "/aINel9503ompOlGKn4sIVMg09Un.jpg",
      genre_ids: [9648, 27, 53],
      id: 838209,
      original_language: "ko",
      original_title: "파묘",
      overview:
        "After tracing the origin of a disturbing supernatural affliction to a wealthy family's ancestral gravesite, a team of paranormal experts relocates the remains—and soon discovers what happens to those who dare to mess with the wrong grave.",
      popularity: 79.739,
      poster_path: "/pQYHouPsDw32FhDLr7E3jmw0WTk.jpg",
      release_date: "2024-02-22",
      title: "Exhuma",
      video: false,
      vote_average: 7.7,
      vote_count: 327,
    },
    {
      adult: false,
      backdrop_path: "/fI6X3Hd8KvtAuOKVdmxckdNzrx.jpg",
      genre_ids: [80, 28, 53],
      id: 581528,
      original_language: "ko",
      original_title: "악인전",
      overview:
        "After barely surviving a violent attack by an elusive serial killer, crime boss Jang Dong-su finds himself forming an unlikely partnership with local detective Jung Tae-seok to catch the sadistic killer simply known as K.",
      popularity: 75.393,
      poster_path: "/oHlM4abRm6BzrRcz9Nup1uidw9H.jpg",
      release_date: "2019-05-15",
      title: "The Gangster, the Cop, the Devil",
      video: false,
      vote_average: 7.792,
      vote_count: 1110,
    },
    {
      adult: false,
      backdrop_path: "/yHEFwHkU2NqRxBrAoGBfuhuqIL1.jpg",
      genre_ids: [35, 28],
      id: 1143019,
      original_language: "fr",
      original_title: "Les Infaillibles",
      overview:
        "When a gang of robbers provokes chaos in Paris and humiliates the police, the Minister of the Interior wants new blood at the helm of the investigation: Alia is from Marseille, fiery-tempered and unmanageable, Hugo is Parisian, valedictorian and meticulous. In short, they have every reason to hate each other. A forced alliance, for better or for worse, or maybe blossoming into something else?",
      popularity: 83.031,
      poster_path: "/7PoIAvL3Io5v0HyBliXfXZruQTi.jpg",
      release_date: "2024-06-20",
      title: "The Infallibles",
      video: false,
      vote_average: 6.317,
      vote_count: 82,
    },
    {
      adult: false,
      backdrop_path: "/k3wfgR5dRYBtfwisuISJ3H4lgQ0.jpg",
      genre_ids: [16, 12, 28, 14, 10402],
      id: 900667,
      original_language: "ja",
      original_title: "ONE PIECE FILM RED",
      overview:
        "Uta — the most beloved singer in the world. Her voice, which she sings with while concealing her true identity, has been described as “otherworldly.” She will appear in public for the first time at a live concert. As the venue fills with all kinds of Uta fans — excited pirates, the Navy watching closely, and the Straw Hats led by Luffy who simply came to enjoy her sonorous performance — the voice that the whole world has been waiting for is about to resound.",
      popularity: 83.106,
      poster_path: "/ogDXuVkO92GcETZfSofXXemw7gb.jpg",
      release_date: "2022-08-06",
      title: "One Piece Film Red",
      video: false,
      vote_average: 7.208,
      vote_count: 982,
    },
    {
      adult: false,
      backdrop_path: "/hGGC9gKo7CFE3fW07RA587e5kol.jpg",
      genre_ids: [16, 35, 10751, 12],
      id: 14160,
      original_language: "en",
      original_title: "Up",
      overview:
        "Carl Fredricksen spent his entire life dreaming of exploring the globe and experiencing life to its fullest. But at age 78, life seems to have passed him by, until a twist of fate (and a persistent 8-year old Wilderness Explorer named Russell) gives him a new lease on life.",
      popularity: 80.331,
      poster_path: "/mFvoEwSfLqbcWwFsDjQebn9bzFe.jpg",
      release_date: "2009-05-28",
      title: "Up",
      video: false,
      vote_average: 7.958,
      vote_count: 19999,
    },
  ],
  total_pages: 46079,
  total_results: 921572,
};
